version: '3.5'

services:
  server:
    container_name: fluxoagil-server
    depends_on:
      - fluxoagil-db
    build: .
    ports:
      - 5000:5000
    networks:
      - fluxoagil-network
    volumes:
      - .:/fluxoagil
      - pip_cache:/usr/local/lib/python3.10/site-packages
  
  fluxoagil-db:
    container_name: fluxoagil-db
    image: postgres:12
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - fluxoagil-network

volumes:
  pip_cache:
    
networks:
  fluxoagil-network:
    name: fluxoagil-network
    driver: bridge